FreeBSD and Install patch from Bjoern Zeeb - Bugzilla 13238

diff --git a/src/xalanc/configure b/src/xalanc/configure
--- a/src/xalanc/configure
+++ b/src/xalanc/configure
@@ -1049,12 +1049,11 @@ else
 fi
 
 
-# Check for gcc problems
 
 if test "$CXX" = "g++" -o "$CXX" = "c++"; then
 
   echo $ac_n "checking whether -fno-elide-constructors works correctly""... $ac_c" 1>&6
-echo "configure:1058: checking whether -fno-elide-constructors works correctly" >&5
+echo "configure:1057: checking whether -fno-elide-constructors works correctly" >&5
 
   old_cxxflags=$CXXFLAGS
   CXXFLAGS="$CXXFLAGS -fno-elide-constructors"
@@ -1068,14 +1067,14 @@ cross_compiling=$ac_cv_prog_cxx_cross
 
 
   cat > conftest.$ac_ext <<EOF
-#line 1072 "configure"
+#line 1071 "configure"
 #include "confdefs.h"
 #include <vector>
 int main() {
 
 ; return 0; }
 EOF
-if { (eval echo configure:1079: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1078: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   echo "$ac_t""yes" 1>&6
 else
@@ -1097,7 +1096,7 @@ else { echo "configure: error: can not run $ac_config_sub" 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking host system type""... $ac_c" 1>&6
-echo "configure:1101: checking host system type" >&5
+echo "configure:1100: checking host system type" >&5
 
 host_alias=$host
 case "$host_alias" in
@@ -1121,6 +1120,8 @@ echo "$ac_t""$host" 1>&6
 case "${host}" in
         *-*-solaris*)   platform=SOLARIS ;;
         *-*-linux*)     platform=LINUX ;;
+        *-*-freebsd*)   platform=FREEBSD ;;
+        *-*-netbsd*)    platform=NETBSD ;;
         *-*-irix*)      platform=IRIX ;;
         *-*-aix*)       platform=AIX ;;
         *-*-hp*)        platform=HPUX ;
@@ -1134,6 +1135,262 @@ case "${host}" in
         *-apple-darwin*)       platform=MACOSX ;;
         *)              platform=UNKNOWN ;;
 esac
+
+echo $ac_n "checking how to run the C++ preprocessor""... $ac_c" 1>&6
+echo "configure:1141: checking how to run the C++ preprocessor" >&5
+if test -z "$CXXCPP"; then
+if eval "test \"`echo '$''{'ac_cv_prog_CXXCPP'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_ext=C
+# CXXFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='${CXX-g++} -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cxx_cross
+  CXXCPP="${CXX-g++} -E"
+  cat > conftest.$ac_ext <<EOF
+#line 1154 "configure"
+#include "confdefs.h"
+#include <stdlib.h>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1159: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  :
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  CXXCPP=/lib/cpp
+fi
+rm -f conftest*
+  ac_cv_prog_CXXCPP="$CXXCPP"
+ac_ext=C
+# CXXFLAGS is not in ac_cpp because -g, -O, etc. are not valid cpp options.
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='${CXX-g++} -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext 1>&5'
+ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS 1>&5'
+cross_compiling=$ac_cv_prog_cxx_cross
+fi
+fi
+CXXCPP="$ac_cv_prog_CXXCPP"
+echo "$ac_t""$CXXCPP" 1>&6
+
+echo $ac_n "checking for ANSI C header files""... $ac_c" 1>&6
+echo "configure:1184: checking for ANSI C header files" >&5
+if eval "test \"`echo '$''{'ac_cv_header_stdc'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1189 "configure"
+#include "confdefs.h"
+#include <stdlib.h>
+#include <stdarg.h>
+#include <string.h>
+#include <float.h>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:1197: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  ac_cv_header_stdc=yes
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  ac_cv_header_stdc=no
+fi
+rm -f conftest*
+
+if test $ac_cv_header_stdc = yes; then
+  # SunOS 4.x string.h does not declare mem*, contrary to ANSI.
+cat > conftest.$ac_ext <<EOF
+#line 1214 "configure"
+#include "confdefs.h"
+#include <string.h>
+EOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  egrep "memchr" >/dev/null 2>&1; then
+  :
+else
+  rm -rf conftest*
+  ac_cv_header_stdc=no
+fi
+rm -f conftest*
+
+fi
+
+if test $ac_cv_header_stdc = yes; then
+  # ISC 2.0.2 stdlib.h does not declare free, contrary to ANSI.
+cat > conftest.$ac_ext <<EOF
+#line 1232 "configure"
+#include "confdefs.h"
+#include <stdlib.h>
+EOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  egrep "free" >/dev/null 2>&1; then
+  :
+else
+  rm -rf conftest*
+  ac_cv_header_stdc=no
+fi
+rm -f conftest*
+
+fi
+
+if test $ac_cv_header_stdc = yes; then
+  # /bin/cc in Irix-4.0.5 gets non-ANSI ctype macros unless using -ansi.
+if test "$cross_compiling" = yes; then
+  :
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1253 "configure"
+#include "confdefs.h"
+#ifdef __cplusplus
+extern "C" void exit(int);
+#endif
+#include <ctype.h>
+#define ISLOWER(c) ('a' <= (c) && (c) <= 'z')
+#define TOUPPER(c) (ISLOWER(c) ? 'A' + ((c) - 'a') : (c))
+#define XOR(e, f) (((e) && !(f)) || (!(e) && (f)))
+int main () { int i; for (i = 0; i < 256; i++)
+if (XOR (islower (i), ISLOWER (i)) || toupper (i) != TOUPPER (i)) exit(2);
+exit (0); }
+
+EOF
+if { (eval echo configure:1267: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  :
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  ac_cv_header_stdc=no
+fi
+rm -fr conftest*
+fi
+
+fi
+fi
+
+echo "$ac_t""$ac_cv_header_stdc" 1>&6
+if test $ac_cv_header_stdc = yes; then
+  cat >> confdefs.h <<\EOF
+#define STDC_HEADERS 1
+EOF
+
+fi
+
+for ac_func in mbstowcs
+do
+echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
+echo "configure:1293: checking for $ac_func" >&5
+if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1298 "configure"
+#include "confdefs.h"
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func(); below.  */
+#include <assert.h>
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char $ac_func();
+
+int main() {
+
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined (__stub_$ac_func) || defined (__stub___$ac_func)
+choke me
+#else
+$ac_func();
+#endif
+
+; return 0; }
+EOF
+if { (eval echo configure:1324: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_func_$ac_func=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_func_$ac_func=no"
+fi
+rm -f conftest*
+fi
+
+if eval "test \"`echo '$ac_cv_func_'$ac_func`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_func=HAVE_`echo $ac_func | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_func 1
+EOF
+ 
+else
+  echo "$ac_t""no" 1>&6
+fi
+done
+
+if test x"$ac_cv_func_mbstowcs" = x"no"; then
+	WCSTOMBS="-DXALAN_USE_XERCES_LOCAL_CODEPAGE_TRANSCODERS"
+else
+echo $ac_n "checking if mbstowcs can count only""... $ac_c" 1>&6
+echo "configure:1352: checking if mbstowcs can count only" >&5
+if test "$cross_compiling" = yes; then
+  WCSTOMBS="-DXALAN_USE_XERCES_LOCAL_CODEPAGE_TRANSCODERS";
+	 echo "$ac_t""cross-compiling default" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1358 "configure"
+#include "confdefs.h"
+#ifdef __cplusplus
+extern "C" void exit(int);
+#endif
+
+#if STDC_HEADERS
+#include <stdlib.h>
+#endif
+
+int main(int argc, char *argv[])
+{
+	wchar_t in[5] = { 0x74, 0x65, 0x73, 0x74, 0x00 };
+
+	if (wcstombs(0, in, 0) == -1) {
+		exit(1);
+	}
+
+	exit(0);
+}
+EOF
+if { (eval echo configure:1379: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  echo "$ac_t""yes" 1>&6
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  WCSTOMBS="-DXALAN_USE_XERCES_LOCAL_CODEPAGE_TRANSCODERS";
+	 echo "$ac_t""no" 1>&6
+fi
+rm -fr conftest*
+fi
+
+fi
+
+
 
 
 cxx=${CXX}
@@ -1161,6 +1418,9 @@ libs=${LIBS}
 
 
 transcoder=${TRANSCODER}
+
+
+wcstombs=${WCSTOMBS}
 
 
 threads=${THREADS}
@@ -1242,7 +1502,7 @@ s%\[%\\&%g
 s%\]%\\&%g
 s%\$%$$%g
 EOF
-DEFS=`sed -f conftest.defs confdefs.h | tr '\n' ' '`
+DEFS=`sed -f conftest.defs confdefs.h | tr '\012' ' '`
 rm -f conftest.defs
 
 
@@ -1325,6 +1585,7 @@ s%@host_alias@%$host_alias%g
 s%@host_cpu@%$host_cpu%g
 s%@host_vendor@%$host_vendor%g
 s%@host_os@%$host_os%g
+s%@CXXCPP@%$CXXCPP%g
 s%@platform@%$platform%g
 s%@cxx@%$cxx%g
 s%@cc@%$cc%g
@@ -1335,6 +1596,7 @@ s%@cflags@%$cflags%g
 s%@ldflags@%$ldflags%g
 s%@libs@%$libs%g
 s%@transcoder@%$transcoder%g
+s%@wcstombs@%$wcstombs%g
 s%@threads@%$threads%g
 s%@bitstobuild@%$bitstobuild%g
 
diff --git a/src/xalanc/runConfigure b/src/xalanc/runConfigure
--- a/src/xalanc/runConfigure
+++ b/src/xalanc/runConfigure
@@ -58,6 +58,9 @@
 # 
 #
 # $Log$
+# Revision 1.2  2003/07/22 10:59:40  blautenb
+# FreeBSD and Install patch from Bjoern Zeeb - Bugzilla 13238
+#
 # Revision 1.1  2003/06/29 03:57:53  blautenb
 # Moved source for sane includes
 #
@@ -140,10 +143,12 @@ usage()
     echo "runConfigure: Helper script to run \"configure\" for one of the supported platforms"
     echo "Usage: runConfigure \"options\""
     echo "       where options may be any of the following:"
-    echo "       -p <platform> (accepts 'aix', 'linux', 'solaris', 'hp-10', 'hp-11', 'irix', 'tru64', 'macosx' )"
+    echo "       -p <platform> (accepts 'aix', 'linux', 'freebsd', 'netbsd', 'solaris',
+            'hp-10', 'hp-11', 'irix', 'tru64', 'macosx')"
     echo "       -c <C compiler name> (e.g. gcc, cc, xlc)"
     echo "       -x <C++ compiler name> (e.g. g++, CC, xlC)"
     echo "       -d (specifies that you want to build debug version)"
+    echo "       -t <transcoder> can be 'icu' (everything else means default)"
     echo "       -r <thread option> can be 'pthread' or 'dce' (only used on HP-11)"
     echo "       -b <bitsToBuild> (accepts '64', '32')"
     echo "       -l <extra linker options>"
@@ -190,6 +195,7 @@ fi
 # Set up the default values for each parameter
 debug=off                # by default debug is off
 bitsToBuild=32           # by default 32 bit build assumed
+transcoder=default       # by default use default transcoder
 
 while [ $# -gt 0 ]
    do
@@ -205,6 +211,9 @@ while [ $# -gt 0 ]
 
    -d) 
         debug=on; shift;;
+
+   -t)
+        transcoder=$2; shift 2;;
 
    -r) 
         thread=$2; shift 2;;
@@ -241,6 +250,7 @@ echo "C Compiler: $ccompiler"
 echo "C++ Compiler: $cppcompiler"
 echo "Extra compile options: $compileroptions"
 echo "Extra link options: $linkeroptions"
+echo "Transcoder: $transcoder"
 echo "Thread option: $thread"
 echo "bitsToBuild option: $bitsToBuild"
 echo "Extra configure options: $configureoptions"
@@ -251,7 +261,7 @@ echo "Extra configure options: $configureoptions"
 #
 
 case $platform in
-   aix | linux | solaris | hp-10 | hp-11 | irix | tru64 | macosx)
+   aix | linux | freebsd | netbsd | solaris | hp-10 | hp-11 | irix | tru64 | macosx)
        # platform has been recognized
        ;;
    *)
@@ -288,7 +298,7 @@ fi
 
 #
 #  aix | linux | hp-11 | solaris |
-#  hp-10 | freebsd | irix | openserver | unixware | os400 | ptx | tru64 | macosx
+#  hp-10 | freebsd | netbsd | irix | openserver | unixware | os400 | ptx | tru64 | macosx
 #
 if test $bitsToBuild = 64; then
     bitstobuildDefines=" -DXML_BITSTOBUILD_64 "
@@ -339,7 +349,33 @@ BITSTOBUILD=$bitsToBuild
 export BITSTOBUILD
 
 #
-# Check for the threading option only for hp-11
+# Now check whether to use 'icu' as transcoder
+#
+TRANSCODER=
+if test $transcoder; then
+    case $transcoder in
+        icu)
+	    if test ${ICUROOT}o = "o"; then
+		    echo '***Error*** ICUROOT environment variable not defined. Exiting...';
+		    exit ${ERROR_EXIT_CODE};
+            fi
+	    transcodingDefines="-I${ICUROOT}/include";
+	    transcodingLibs="-L${ICUROOT} -L${ICUROOT}/lib -L${ICUROOT}/data";
+	    TRANSCODER=ICU;;
+
+	default)
+	    ;;
+	*)
+	    echo "Unknown transcoder '$transcoder'. Using default."
+	    ;;
+    esac
+fi
+
+export TRANSCODER
+
+
+#
+# Check for the threading option
 #
 
 threadingLibs="-lpthread"
@@ -360,6 +396,10 @@ if test $platform = "hp-11"; then
     fi
 elif test $platform = "aix"; then
     threadingLibs="-lpthreads"
+elif test $platform = "freebsd"; then
+    threadingLibs="-pthread -lc_r"
+elif test $platform = "netbsd"; then
+    threadingLibs="-pthread -lpthread"
 elif test $platform = "hp-10"; then
     threadingLibs="-lcma"
     threadingDefines="-DXML_USE_DCE"
